version: '3.8'
services:
  postgres:
    container_name: postgresql-personal
    image: postgres:16
    ports:
      - '5532:5432'
    volumes:
      - ./db-scripts/create-extensions-db.sh:/docker-entrypoint-initdb.d/create-extensions-db.sh
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker-postgres-db.env
  azure-sql-edge-data: 
    image: mcr.microsoft.com/azure-sql-edge  
    environment:
      - docker-azure-sql-db.env
    ports:
      - "1433:1433"                        # Map container port 1433 to host port 1433
    volumes:
      - ./azure-sql-edge-data:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'


volumes:
  azure-sql-edge-data:
  db:
